//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEventSocket.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEventSocket.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Name: CHANNEL_DATA
        ///Core-UUID: 8694f653-55e0-42ed-98d8-4983e2b6d248
        ///FreeSWITCH-Hostname: dan-win8-dev
        ///FreeSWITCH-Switchname: dan-win8-dev
        ///FreeSWITCH-IPv4: 172.16.50.134
        ///FreeSWITCH-IPv6: 2001%3A0%3A5ef5%3A79fd%3A1c45%3A341e%3A53ef%3Acd79
        ///Event-Date-Local: 2015-01-06%2015%3A12%3A37
        ///Event-Date-GMT: Tue,%2006%20Jan%202015%2015%3A12%3A37%20GMT
        ///Event-Date-Timestamp: 1420557157955591
        ///Event-Calling-File: mod_event_socket.c
        ///Event-Calling-Function: parse_command
        ///Event-Calling-Line-Number: 1875
        ///Event-Sequence: 58 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example1 {
            get {
                return ResourceManager.GetString("Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Name: CHANNEL_DATA
        ///Core-UUID: 8694f653-55e0-42ed-98d8-4983e2b6d248
        ///FreeSWITCH-Hostname: dan-win8-dev
        ///FreeSWITCH-Switchname: dan-win8-dev
        ///FreeSWITCH-IPv4: 172.16.50.134
        ///FreeSWITCH-IPv6: 2001%3A0%3A5ef5%3A79fd%3A1c45%3A341e%3A53ef%3Acd79
        ///Event-Date-Local: 2015-01-06%2015%3A59%3A16
        ///Event-Date-GMT: Tue,%2006%20Jan%202015%2015%3A59%3A16%20GMT
        ///Event-Date-Timestamp: 1420559956095134
        ///Event-Calling-File: mod_event_socket.c
        ///Event-Calling-Function: parse_command
        ///Event-Calling-Line-Number: 1875
        ///Event-Sequence: 64 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example2 {
            get {
                return ResourceManager.GetString("Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Name: CHANNEL_DATA
        ///Core-UUID: 8694f653-55e0-42ed-98d8-4983e2b6d248
        ///FreeSWITCH-Hostname: dan-win8-dev
        ///FreeSWITCH-Switchname: dan-win8-dev
        ///FreeSWITCH-IPv4: 172.16.50.134
        ///FreeSWITCH-IPv6: 2001%3A0%3A5ef5%3A79fd%3A1c45%3A341e%3A53ef%3Acd79
        ///Event-Date-Local: 2015-01-06%2015%3A11%3A55
        ///Event-Date-GMT: Tue,%2006%20Jan%202015%2015%3A11%3A55%20GMT
        ///Event-Date-Timestamp: 1420557115134938
        ///Event-Calling-File: mod_event_socket.c
        ///Event-Calling-Function: parse_command
        ///Event-Calling-Line-Number: 1875
        ///Event-Sequence: 57 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example3 {
            get {
                return ResourceManager.GetString("Example3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Name: CHANNEL_DATA
        ///Core-UUID: 8694f653-55e0-42ed-98d8-4983e2b6d248
        ///FreeSWITCH-Hostname: dan-win8-dev
        ///FreeSWITCH-Switchname: dan-win8-dev
        ///FreeSWITCH-IPv4: 172.16.50.134
        ///FreeSWITCH-IPv6: 2001%3A0%3A5ef5%3A79fd%3A1c45%3A341e%3A53ef%3Acd79
        ///Event-Date-Local: 2015-01-06%2016%3A43%3A57
        ///Event-Date-GMT: Tue,%2006%20Jan%202015%2016%3A43%3A57%20GMT
        ///Event-Date-Timestamp: 1420562637535277
        ///Event-Calling-File: mod_event_socket.c
        ///Event-Calling-Function: parse_command
        ///Event-Calling-Line-Number: 1875
        ///Event-Sequence: 71 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example4 {
            get {
                return ResourceManager.GetString("Example4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Name: CHANNEL_DATA
        ///Core-UUID: 8694f653-55e0-42ed-98d8-4983e2b6d248
        ///FreeSWITCH-Hostname: dan-win8-dev
        ///FreeSWITCH-Switchname: dan-win8-dev
        ///FreeSWITCH-IPv4: 172.16.50.134
        ///FreeSWITCH-IPv6: 2001%3A0%3A5ef5%3A79fd%3A1c45%3A341e%3A53ef%3Acd79
        ///Event-Date-Local: 2015-01-06%2016%3A49%3A28
        ///Event-Date-GMT: Tue,%2006%20Jan%202015%2016%3A49%3A28%20GMT
        ///Event-Date-Timestamp: 1420562968514127
        ///Event-Calling-File: mod_event_socket.c
        ///Event-Calling-Function: parse_command
        ///Event-Calling-Line-Number: 1875
        ///Event-Sequence: 73 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example5 {
            get {
                return ResourceManager.GetString("Example5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event-Name: CHANNEL_DATA
        ///Core-UUID: 93444bb0-338e-4475-83b1-4d9931e536ae
        ///FreeSWITCH-Hostname: dan-win8-dev
        ///FreeSWITCH-Switchname: dan-win8-dev
        ///FreeSWITCH-IPv4: 172.16.50.134
        ///FreeSWITCH-IPv6: 2001%3A0%3A9d38%3A90d7%3A876%3Aa68%3Aa72c%3Ab644
        ///Event-Date-Local: 2015-01-07%2008%3A56%3A01
        ///Event-Date-GMT: Wed,%2007%20Jan%202015%2008%3A56%3A01%20GMT
        ///Event-Date-Timestamp: 1420620961716607
        ///Event-Calling-File: mod_event_socket.c
        ///Event-Calling-Function: parse_command
        ///Event-Calling-Line-Number: 1875
        ///Event-Sequence: 1058 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Example6 {
            get {
                return ResourceManager.GetString("Example6", resourceCulture);
            }
        }
    }
}
